import java.util.Scanner;
public class SubscriptionClass {
	String subscriptionName;
	int userId;
	int subscriptionId;
	PaymentType paymentType ;
    private static int autoGeneratedId = 1;
    public SubscriptionClass(String subscriptionName, int userId, PaymentType paymentType){
    	 this.subscriptionName = subscriptionName;
    	 this.userId = userId;
    	 this.subscriptionId = autoGeneratedId++;
    	 this.paymentType = paymentType;
     }
     public int getTotalSubscriptionId() {
    	 return autoGeneratedId;
     }
     public PaymentType getPaymentType(int userId){
    	 return this.paymentType;
     }
     
     public void setPaymentType(String paymentType){
    	 if(paymentType.equals(PaymentType.Basic))
    	 {
    	 this.paymentType =PaymentType.Basic ;
    	 }
    	 else if(paymentType.equals(PaymentType.Premium))
    	 {
    		 this.paymentType =PaymentType.Premium ;
    	 }
    	 else 
    	 {
    		 this.paymentType =PaymentType.Free ;
		 } 
    	 
     }
}
